<a href="https://colab.research.google.com/github/au950021135042/NM-Project-AI-AND-ML-/blob/main/Heart_Disease_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/heart_disease_health_indicators_BRFSS2015.csv')



In [ ]:
df.head()

HeartDiseaseorAttack  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                   0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1                   0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2                   0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3                   0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4                   0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   Diabetes  PhysActivity  Fruits  ...  AnyHealthcare  NoDocbcCost  GenHlth  \
0       0.0           0.0     0.0  ...            1.0          0.0      5.0   
1       0.0           1.0     0.0  ...            0.0          1.0      3.0   
2       0.0           0.0     1.0  ...            1.0          1.0      5.0   
3       0.0           1.0     1.0  ...            1.0          0.0      2.0   
4       0.0           1.0     1.0  ...            1.0          0.0      2.0   

   MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income  
0      18.0      15.0       1.0  0.0   9.0        4.0     3.0  
1       0.0       0.0       0.0  0.0   7.0        6.0     1.0  
2      30.0      30.0       1.0  0.0   9.0        4.0     8.0  
3       0.0       0.0       0.0  0.0  11.0        3.0     6.0  
4       3.0       0.0       0.0  0.0  11.0        5.0     4.0  

[5 rows x 22 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70177 entries, 0 to 70176
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   HeartDiseaseorAttack  70177 non-null  float64
 1   HighBP                70177 non-null  float64
 2   HighChol              70177 non-null  float64
 3   CholCheck             70177 non-null  float64
 4   BMI                   70177 non-null  float64
 5   Smoker                70177 non-null  float64
 6   Stroke                70177 non-null  float64
 7   Diabetes              70177 non-null  float64
 8   PhysActivity          70177 non-null  float64
 9   Fruits                70177 non-null  float64
 10  Veggies               70177 non-null  float64
 11  HvyAlcoholConsump     70177 non-null  float64
 12  AnyHealthcare         70177 non-null  float64
 13  NoDocbcCost           70177 non-null  float64
 14  GenHlth               70177 non-null  float64
 15  MentHlth           

In [ ]:
df.isnull().sum()

HeartDiseaseorAttack    0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
Diabetes                0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [ ]:
obj_list=df.select_dtypes(include='object').columns
obj_list

Index([], dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for obj in obj_list:
        df[obj] = le.fit_transform(df[obj].astype(str))
df.head()

HeartDiseaseorAttack  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                   0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1                   0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2                   0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3                   0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4                   0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   Diabetes  PhysActivity  Fruits  ...  AnyHealthcare  NoDocbcCost  GenHlth  \
0       0.0           0.0     0.0  ...            1.0          0.0      5.0   
1       0.0           1.0     0.0  ...            0.0          1.0      3.0   
2       0.0           0.0     1.0  ...            1.0          1.0      5.0   
3       0.0           1.0     1.0  ...            1.0          0.0      2.0   
4       0.0           1.0     1.0  ...            1.0          0.0      2.0   

   MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income  
0      18.0      15.0       1.0  0.0   9.0        4.0     3.0  
1       0.0       0.0       0.0  0.0   7.0        6.0     1.0  
2      30.0      30.0       1.0  0.0   9.0        4.0     8.0  
3       0.0       0.0       0.0  0.0  11.0        3.0     6.0  
4       3.0       0.0       0.0  0.0  11.0        5.0     4.0  

[5 rows x 22 columns]

In [ ]:
correlation=df.corr()
correlation

HeartDiseaseorAttack    HighBP  HighChol  CholCheck  \
HeartDiseaseorAttack              1.000000  0.209248  0.172264   0.040863   
HighBP                            0.209248  1.000000  0.293594   0.097538   
HighChol                          0.172264  0.293594  1.000000   0.086457   
CholCheck                         0.040863  0.097538  0.086457   1.000000   
BMI                               0.060597  0.234110  0.115813   0.038350   
Smoker                            0.110345  0.102397  0.086401  -0.010831   
Stroke                            0.207598  0.127947  0.091781   0.021950   
Diabetes                          0.179503  0.274349  0.204270   0.065848   
PhysActivity                     -0.084796 -0.123342 -0.080975   0.003907   
Fruits                           -0.020214 -0.042021 -0.040824   0.021933   
Veggies                          -0.034749 -0.064227 -0.040952   0.004715   
HvyAlcoholConsump                -0.027913 -0.006189 -0.014397  -0.020653   
AnyHealthcare                     0.021445  0.034805  0.046850   0.113730   
NoDocbcCost                       0.030960  0.010201  0.008775  -0.063132   
GenHlth                           0.246870  0.299220  0.202990   0.043297   
MentHlth                          0.068887  0.052224  0.059633  -0.011384   
PhysHlth                          0.176189  0.159055  0.119632   0.034436   
DiffWalk                          0.205547  0.221615  0.139878   0.041152   
Sex                               0.085112  0.050213  0.032418  -0.022043   
Age                               0.212863  0.338954  0.264976   0.088241   
Education                        -0.083400 -0.132106 -0.058863   0.006146   
Income                           -0.129193 -0.160324 -0.072577   0.022689   

                           BMI    Smoker    Stroke  Diabetes  PhysActivity  \
HeartDiseaseorAttack  0.060597  0.110345  0.207598  0.179503     -0.084796   
HighBP                0.234110  0.102397  0.127947  0.274349     -0.123342   
HighChol              0.115813  0.086401  0.091781  0.204270     -0.080975   
CholCheck             0.038350 -0.010831  0.021950  0.065848      0.003907   
BMI                   1.000000  0.014489  0.019564  0.242410     -0.162021   
Smoker                0.014489  1.000000  0.060879  0.057346     -0.085253   
Stroke                0.019564  0.060879  1.000000  0.102756     -0.073282   
Diabetes              0.242410  0.057346  0.102756  1.000000     -0.121657   
PhysActivity         -0.162021 -0.085253 -0.073282 -0.121657      1.000000   
Fruits               -0.094967 -0.068206 -0.019863 -0.040989      0.137960   
Veggies              -0.072079 -0.025534 -0.042927 -0.060954      0.151581   
HvyAlcoholConsump    -0.052857  0.101427 -0.016572 -0.058818      0.014066   
AnyHealthcare        -0.012941 -0.015956  0.009884  0.010797      0.037259   
NoDocbcCost           0.062277  0.043489  0.039644  0.035064     -0.059184   
GenHlth               0.261303  0.152563  0.172559  0.299765     -0.264912   
MentHlth              0.090088  0.079370  0.072149  0.068903     -0.124239   
PhysHlth              0.130955  0.110402  0.148765  0.171699     -0.218157   
DiffWalk              0.214101  0.114696  0.171872  0.221364     -0.257069   
Sex                   0.046662  0.094757 -0.001039  0.027820      0.032567   
Age                  -0.035059  0.135438  0.124777  0.177274     -0.086341   
Education            -0.124867 -0.142846 -0.068695 -0.131010      0.193681   
Income               -0.112638 -0.112277 -0.125049 -0.163279      0.188407   

                        Fruits  ...  AnyHealthcare  NoDocbcCost   GenHlth  \
HeartDiseaseorAttack -0.020214  ...       0.021445     0.030960  0.246870   
HighBP               -0.042021  ...       0.034805     0.010201  0.299220   
HighChol             -0.040824  ...       0.046850     0.008775  0.202990   
CholCheck             0.021933  ...       0.113730    -0.063132  0.043297   
BMI                  -0.094967  ...      -0.012941     0.062277  0.261

In [ ]:
X = df.drop('HeartDiseaseorAttack', axis=1).values
y = df['HeartDiseaseorAttack'].values
from sklearn.model_selection import train_test_split
np.random.seed(41)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier().fit(X_train, y_train)
knn.score(X_train, y_train)

0.9192842456690349

In [ ]:
from sklearn.linear_model import LogisticRegression
np.random.seed(41)
lr = LogisticRegression().fit(X_train, y_train)
lr.score(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9104696374407101

In [ ]:
from sklearn.ensemble import RandomForestClassifier
np.random.seed(41)
rf = RandomForestClassifier().fit(X_train,y_train)
rf.score(X_train, y_train)

0.9982492925920649

In [ ]:
from sklearn.metrics import confusion_matrix
prediction=lr.predict(X_train)
prediction
confusion_matrix=confusion_matrix(y_train,prediction)
confusion_matrix

array([[44253,   366],
       [ 4032,   472]])

In [ ]:
from sklearn.metrics import confusion_matrix
prediction=knn.predict(X_train)
prediction
confusion_matrix=confusion_matrix(y_train,prediction)
confusion_matrix

array([[44195,   424],
       [ 3541,   963]])

In [ ]:
from sklearn.metrics import confusion_matrix
prediction=rf.predict(X_train)
prediction
confusion_matrix=confusion_matrix(y_train,prediction)
confusion_matrix

array([[44609,    10],
       [   76,  4428]])

In [ ]:
y=df.HeartDiseaseorAttack.values
x=df.drop(['HeartDiseaseorAttack'],axis=1)
x

HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  Diabetes  \
0         1.0       1.0        1.0  40.0     1.0     0.0       0.0   
1         0.0       0.0        0.0  25.0     1.0     0.0       0.0   
2         1.0       1.0        1.0  28.0     0.0     0.0       0.0   
3         1.0       0.0        1.0  27.0     0.0     0.0       0.0   
4         1.0       1.0        1.0  24.0     0.0     0.0       0.0   
...       ...       ...        ...   ...     ...     ...       ...   
70172     0.0       0.0        1.0  26.0     1.0     0.0       0.0   
70173     0.0       0.0        1.0  28.0     0.0     0.0       2.0   
70174     0.0       0.0        1.0  26.0     1.0     0.0       0.0   
70175     1.0       0.0        1.0  20.0     1.0     0.0       0.0   
70176     1.0       1.0        1.0  32.0     1.0     0.0       2.0   

       PhysActivity  Fruits  Veggies  ...  AnyHealthcare  NoDocbcCost  \
0               0.0     0.0      1.0  ...            1.0          0.0   
1               1.0     0.0      0.0  ...            0.0          1.0   
2               0.0     1.0      0.0  ...            1.0          1.0   
3               1.0     1.0      1.0  ...            1.0          0.0   
4               1.0     1.0      1.0  ...            1.0          0.0   
...             ...     ...      ...  ...            ...          ...   
70172           0.0     0.0      1.0  ...            1.0          0.0   
70173           1.0     1.0      1.0  ...            1.0          1.0   
70174           0.0     1.0      1.0  ...            1.0          0.0   
70175           1.0     0.0      1.0  ...            1.0          0.0   
70176           0.0     0.0      1.0  ...            1.0          0.0   

       GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income  
0          5.0      18.0      15.0       1.0  0.0   9.0        4.0     3.0  
1          3.0       0.0       0.0       0.0  0.0   7.0        6.0     1.0  
2          5.0      30.0      30.0       1.0  0.0   9.0        4.0     8.0  
3          2.0       0.0       0.0       0.0  0.0  11.0        3.0     6.0  
4          2.0       3.0       0.0       0.0  0.0  11.0        5.0     4.0  
...        ...       ...       ...       ...  ...   ...        ...     ...  
70172      2.0       0.0       0.0       0.0  1.0   9.0        4.0     8.0  
70173      3.0       0.0       0.0       0.0  0.0   8.0        6.0     7.0  
70174      5.0       0.0      30.0       1.0  1.0   8.0        5.0     2.0  
70175      3.0       6.0       0.0       0.0  0.0   9.0        5.0     8.0  
70176      4.0      30.0      21.0       0.0  1.0  10.0        6.0     8.0  

[70177 rows x 21 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train=x_train.T
x_test=x_test.T
y_train=y_train.T
y_test=y_test.T

In [ ]:
from sklearn.linear_model import LogisticRegression
accuracies={}
lr=LogisticRegression()
lr.fit(x_train.T,y_train.T)
acc=lr.score(x_train.T,y_train.T)*100
print('Test accuracy {:.2f}%'.format(acc))

Test accuracy 90.99%


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
